# Generated by Django 4.2.23 on 2025-07-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('funcao', models.CharField(choices=[('diretoria', 'Diretoria'), ('financeiro', 'Financeiro'), ('gestor_frota', 'Gestor de Frota'), ('operacional', 'Operacional'), ('compras', 'Compras'), ('manutencao', 'Manutenção'), ('administrativo', 'Administrativo')], max_length=20, verbose_name='Função')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subusuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Principal')),
            ],
            options={
                'verbose_name': 'Subusuário',
                'verbose_name_plural': 'Subusuários',
                'ordering': ['nome'],
                'unique_together': {('email', 'usuario_principal')},
            },
        ),
    ]
