# Generated by Django 4.2.23 on 2025-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subusuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Módulo')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='bi-circle', max_length=50, verbose_name='Ícone Bootstrap')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Módulo de Acesso',
                'verbose_name_plural': 'Módulos de Acesso',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Perfil')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modulos', models.ManyToManyField(to='subusuarios.moduloacesso', verbose_name='Módulos Incluídos')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='subusuario',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='subusuarios', to='subusuarios.moduloacesso', verbose_name='Módulos de Acesso'),
        ),
    ]
