# Generated by Django 4.2.23 on 2025-07-16 20:50

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subusuarios', '0002_moduloacesso_perfilacesso_subusuario_modulos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subusuario',
            unique_together={('email', 'usuario_principal')},
        ),
        migrations.AddField(
            model_name='subusuario',
            name='convite_enviado',
            field=models.BooleanField(default=False, verbose_name='Convite Enviado'),
        ),
        migrations.AddField(
            model_name='subusuario',
            name='login',
            field=models.CharField(default='usuario_temp', help_text='Nome de usuário para acesso ao sistema', max_length=50, verbose_name='Login/Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subusuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='Primeiro Acesso'),
        ),
        migrations.AddField(
            model_name='subusuario',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='subusuario',
            name='senha_definida',
            field=models.BooleanField(default=False, verbose_name='Senha Definida'),
        ),
        migrations.AddField(
            model_name='subusuario',
            name='token_convite',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de Convite'),
        ),
        migrations.AlterUniqueTogether(
            name='subusuario',
            unique_together={('login', 'usuario_principal'), ('email', 'usuario_principal')},
        ),
    ]
