# Generated by Django 4.2.23 on 2025-07-10 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao_curta', models.CharField(max_length=255, verbose_name='Descrição Curta')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Base')),
                ('icone', models.CharField(default='fas fa-cog', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('imagem', models.ImageField(blank=True, upload_to='servicos/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data do Agendamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
