# Generated by Django 4.2.23 on 2025-07-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('km', models.IntegerField(verbose_name='Quilometragem')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('dianteiro_esquerdo', 'Dianteiro Esquerdo'), ('dianteiro_direito', 'Dianteiro Direito'), ('traseiro_esquerdo_1', 'Traseiro Esquerdo 1'), ('traseiro_direito_1', 'Traseiro Direito 1'), ('traseiro_esquerdo_2', 'Traseiro Esquerdo 2'), ('traseiro_direito_2', 'Traseiro Direito 2'), ('estepe', 'Estepe')], max_length=30, verbose_name='Posição no Veículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('medida', models.CharField(choices=[('225/75/16', '225/75/16'), ('215/75/17.5', '215/75/17.5'), ('235/75/17.5', '235/75/17.5'), ('275/80/22.5', '275/80/22.5'), ('295/80/22.5', '295/80/22.5')], max_length=20, verbose_name='Medida do Pneu')),
                ('pressao', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Pressão (PSI)')),
                ('profundidade_sulco', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Profundidade do Sulco (mm)')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('data_instalacao', models.DateField(verbose_name='Data de Instalação')),
                ('km_instalacao', models.IntegerField(verbose_name='KM na Instalação')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('lote_fabricacao', models.CharField(max_length=50, verbose_name='Lote de Fabricação')),
                ('numero_serie', models.CharField(max_length=50, verbose_name='Número de Série')),
                ('marca_fogo', models.CharField(max_length=50, verbose_name='Marca Fogo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Técnicas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'ordering': ['-data_cadastro'],
                'unique_together': {('veiculo', 'posicao')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('instalacao', 'Instalação'), ('manutencao', 'Manutenção'), ('troca', 'Troca'), ('remocao', 'Remoção')], max_length=20, verbose_name='Tipo de Evento')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('km_evento', models.IntegerField(verbose_name='KM no Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='frota.pneu')),
            ],
            options={
                'verbose_name': 'Histórico de Pneu',
                'verbose_name_plural': 'Históricos de Pneus',
                'ordering': ['-data_evento'],
            },
        ),
    ]
