# Generated by Django 4.2.23 on 2025-07-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_eixos', models.PositiveSmallIntegerField(unique=True, verbose_name='Quantidade de Eixos')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('configuracao', models.CharField(max_length=20, verbose_name='Configuração (ex: 4x2, 6x4)')),
                ('peso_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Máximo (kg)')),
            ],
            options={
                'verbose_name': 'Configuração de Eixo',
                'verbose_name_plural': 'Configurações de Eixos',
                'ordering': ['quantidade_eixos'],
            },
        ),
        migrations.CreateModel(
            name='CorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome da Cor')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, verbose_name='Código Hex')),
                ('popular', models.BooleanField(default=False, verbose_name='Cor Popular')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cor de Veículo',
                'verbose_name_plural': 'Cores de Veículos',
                'ordering': ['-popular', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Marca')),
                ('pais_origem', models.CharField(default='Brasil', max_length=50, verbose_name='País de Origem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca de Veículo',
                'verbose_name_plural': 'Marcas de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PneuEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('medida', models.CharField(choices=[('225/75/16', '225/75/16'), ('215/75/17.5', '215/75/17.5'), ('235/75/17.5', '235/75/17.5'), ('275/80/22.5', '275/80/22.5'), ('295/80/22.5', '295/80/22.5'), ('315/80/22.5', '315/80/22.5')], max_length=20, verbose_name='Medida')),
                ('tipo', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('reformado', 'Reformado')], max_length=20, verbose_name='Tipo')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Série')),
                ('dot', models.CharField(max_length=10, verbose_name='DOT (Data Fabricação)')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('reformado', 'Reformado'), ('descartado', 'Descartado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pneu em Estoque',
                'verbose_name_plural': 'Pneus em Estoque',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('caminhao', 'Caminhão'), ('carreta', 'Carreta'), ('semi_reboque', 'Semi-reboque'), ('reboque', 'Reboque'), ('bitrem', 'Bitrem'), ('rodotrem', 'Rodotrem')], max_length=20, unique=True, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=17, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quantidade_eixos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de Eixos'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=11, verbose_name='RENAVAM'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('ano_inicio', models.PositiveSmallIntegerField(verbose_name='Ano de Início')),
                ('ano_fim', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Fim')),
                ('quantidade_eixos', models.PositiveSmallIntegerField(verbose_name='Quantidade de Eixos')),
                ('capacidade_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidade de Carga (kg)')),
                ('motor_padrao', models.CharField(blank=True, max_length=100, verbose_name='Motor Padrão')),
                ('combustivel', models.CharField(default='Diesel', max_length=20, verbose_name='Combustível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='frota.marcaveiculo')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='frota.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'ordering': ['marca__nome', 'nome'],
                'unique_together': {('marca', 'nome', 'ano_inicio')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('entrada', 'Entrada no Estoque'), ('montagem', 'Montagem no Veículo'), ('remocao', 'Remoção do Veículo'), ('manutencao', 'Manutenção'), ('reforma', 'Reforma'), ('descarte', 'Descarte')], max_length=20, verbose_name='Tipo de Movimento')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('km_veiculo', models.IntegerField(blank=True, null=True, verbose_name='KM do Veículo')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pneu_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='frota.pneuestoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentação',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_motor', models.CharField(blank=True, max_length=20, verbose_name='Potência do Motor')),
                ('torque_motor', models.CharField(blank=True, max_length=20, verbose_name='Torque do Motor')),
                ('transmissao', models.CharField(blank=True, max_length=50, verbose_name='Transmissão')),
                ('freios', models.CharField(blank=True, max_length=50, verbose_name='Sistema de Freios')),
                ('suspensao_dianteira', models.CharField(blank=True, max_length=50, verbose_name='Suspensão Dianteira')),
                ('suspensao_traseira', models.CharField(blank=True, max_length=50, verbose_name='Suspensão Traseira')),
                ('tanque_combustivel', models.CharField(blank=True, max_length=20, verbose_name='Capacidade do Tanque')),
                ('pneus_dianteiros', models.CharField(blank=True, max_length=20, verbose_name='Medida Pneus Dianteiros')),
                ('pneus_traseiros', models.CharField(blank=True, max_length=20, verbose_name='Medida Pneus Traseiros')),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacao', to='frota.modeloveiculo')),
            ],
            options={
                'verbose_name': 'Especificação Técnica',
                'verbose_name_plural': 'Especificações Técnicas',
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_cor', to='frota.corveiculo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_marca', to='frota.marcaveiculo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_modelo', to='frota.modeloveiculo'),
        ),
        migrations.CreateModel(
            name='VinculacaoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('dianteiro_esquerdo', 'Dianteiro Esquerdo'), ('dianteiro_direito', 'Dianteiro Direito'), ('intermediario_esquerdo_1', 'Intermediário Esquerdo 1'), ('intermediario_esquerdo_2', 'Intermediário Esquerdo 2'), ('intermediario_direito_1', 'Intermediário Direito 1'), ('intermediario_direito_2', 'Intermediário Direito 2'), ('traseiro_esquerdo_1', 'Traseiro Esquerdo 1'), ('traseiro_esquerdo_2', 'Traseiro Esquerdo 2'), ('traseiro_direito_1', 'Traseiro Direito 1'), ('traseiro_direito_2', 'Traseiro Direito 2'), ('estepe', 'Estepe')], max_length=30, verbose_name='Posição no Veículo')),
                ('data_montagem', models.DateField(verbose_name='Data de Montagem')),
                ('km_montagem', models.IntegerField(verbose_name='KM na Montagem')),
                ('pressao_atual', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Pressão Atual (PSI)')),
                ('sulco_externo', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sulco Externo (mm)')),
                ('sulco_central', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sulco Central (mm)')),
                ('sulco_interno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Sulco Interno (mm)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_remocao', models.DateField(blank=True, null=True, verbose_name='Data de Remoção')),
                ('km_remocao', models.IntegerField(blank=True, null=True, verbose_name='KM na Remoção')),
                ('motivo_remocao', models.TextField(blank=True, verbose_name='Motivo da Remoção')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('pneu_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculacoes', to='frota.pneuestoque')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus_vinculados', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Vinculação de Pneu',
                'verbose_name_plural': 'Vinculações de Pneus',
                'ordering': ['-data_cadastro'],
                'unique_together': {('veiculo', 'posicao', 'ativo')},
            },
        ),
    ]
